
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Mar 22 2025 12:25:48 IST (Mar 22 2025 06:55:48 UTC)

// Verification Directory fv/mcrb 

module mcrb(mc_rb_ef1_svld_i, gctl_rclk_orst_n_i, skew_addr_cntr_o,
     mc_rb_fuse_vld_i, mc_rb_ef1_sclk_i);
  input mc_rb_ef1_svld_i, gctl_rclk_orst_n_i, mc_rb_fuse_vld_i,
       mc_rb_ef1_sclk_i;
  output [4:0] skew_addr_cntr_o;
  wire mc_rb_ef1_svld_i, gctl_rclk_orst_n_i, mc_rb_fuse_vld_i,
       mc_rb_ef1_sclk_i;
  wire [4:0] skew_addr_cntr_o;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, mc_rb_fuse_vld_q, n_0, n_1;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  DFFR_X2 \skew_addr_cntr_reg[4] (.RN (gctl_rclk_orst_n_i), .CK
       (mc_rb_ef1_sclk_i), .D (n_16), .Q (skew_addr_cntr_o[4]), .QN
       (UNCONNECTED));
  AND2_X2 g460__2398(.A1 (n_13), .A2 (n_15), .ZN (n_16));
  DFFR_X2 \skew_addr_cntr_reg[3] (.RN (gctl_rclk_orst_n_i), .CK
       (mc_rb_ef1_sclk_i), .D (n_14), .Q (skew_addr_cntr_o[3]), .QN
       (UNCONNECTED0));
  XOR2_X1 g462__5107(.A (n_11), .B (skew_addr_cntr_o[4]), .Z (n_15));
  AND2_X2 g465__6260(.A1 (n_13), .A2 (n_12), .ZN (n_14));
  HA_X1 g467__4319(.A (n_6), .B (skew_addr_cntr_o[3]), .CO (n_11), .S
       (n_12));
  DFFR_X2 \skew_addr_cntr_reg[2] (.RN (gctl_rclk_orst_n_i), .CK
       (mc_rb_ef1_sclk_i), .D (n_9), .Q (skew_addr_cntr_o[2]), .QN
       (n_0));
  DFFR_X2 \skew_addr_cntr_reg[0] (.RN (gctl_rclk_orst_n_i), .CK
       (mc_rb_ef1_sclk_i), .D (n_10), .Q (skew_addr_cntr_o[0]), .QN
       (UNCONNECTED1));
  DFFR_X2 \skew_addr_cntr_reg[1] (.RN (gctl_rclk_orst_n_i), .CK
       (mc_rb_ef1_sclk_i), .D (n_8), .Q (skew_addr_cntr_o[1]), .QN
       (UNCONNECTED2));
  NOR2_X1 g468__8428(.A1 (n_5), .A2 (skew_addr_cntr_o[0]), .ZN (n_10));
  AND2_X2 g470__5526(.A1 (n_13), .A2 (n_7), .ZN (n_9));
  AND2_X2 g469__6783(.A1 (n_13), .A2 (n_4), .ZN (n_8));
  HA_X1 g473__3680(.A (n_3), .B (skew_addr_cntr_o[2]), .CO (n_6), .S
       (n_7));
  INV_X2 g471(.A (n_13), .ZN (n_5));
  OAI222_X2 g472__1617(.A1 (n_2), .A2 (skew_addr_cntr_o[4]), .B1 (n_1),
       .B2 (skew_addr_cntr_o[3]), .C1 (mc_rb_ef1_svld_i), .C2
       (mc_rb_fuse_vld_q), .ZN (n_13));
  HA_X1 g475__2802(.A (skew_addr_cntr_o[1]), .B (skew_addr_cntr_o[0]),
       .CO (n_3), .S (n_4));
  NOR4_X2 g474__1705(.A1 (skew_addr_cntr_o[1]), .A2
       (skew_addr_cntr_o[0]), .A3 (skew_addr_cntr_o[3]), .A4
       (skew_addr_cntr_o[2]), .ZN (n_2));
  NAND2_X2 g477__5122(.A1 (skew_addr_cntr_o[4]), .A2 (n_0), .ZN (n_1));
  DFFR_X1 mc_rb_fuse_vld_q_reg(.RN (gctl_rclk_orst_n_i), .CK
       (mc_rb_ef1_sclk_i), .D (mc_rb_fuse_vld_i), .Q (UNCONNECTED3),
       .QN (mc_rb_fuse_vld_q));
endmodule

